"use client";
import { useState } from "react";
import Link from "next/link";
import { createClient } from "@/lib/supabase/client";

export default function LoginPage() {
  const [mode,setMode]=useState<"login"|"signup">("login");
  const [email,setEmail]=useState("");
  const [password,setPassword]=useState("");
  const [busy,setBusy]=useState(false);
  const [message,setMessage]=useState("");
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");try{const supabase=createClient();const result=mode==="login"?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password,options:{emailRedirectTo:window.location.origin+"/app/tree"}});if(result.error)throw result.error;if(mode==="signup"&&!result.data.session)setMessage("Check your email to confirm your account, then sign in.");else window.location.href="/app/tree";}catch(err){setMessage(err instanceof Error?err.message:"Authentication failed.");}finally{setBusy(false);}}
  async function google(){setBusy(true);setMessage("");try{const supabase=createClient();const {error}=await supabase.auth.signInWithOAuth({provider:"google",options:{redirectTo:window.location.origin+"/app/tree"}});if(error)throw error;}catch(err){setMessage(err instanceof Error?err.message:"Google sign-in could not start.");setBusy(false);}}
  return <main className="grid min-h-screen place-items-center bg-[#f8f7f2] px-5 py-12 text-[#24372d]"><div className="w-full max-w-md rounded-[2rem] border border-[#e5e8df] bg-[#fffefa] p-7 shadow-xl shadow-[#244b38]/5 sm:p-9"><Link href="/" className="flex items-center gap-3 text-xl font-semibold"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-[#244b38] text-white">V</span> vansh</Link><p className="mt-8 text-xs font-semibold uppercase tracking-widest text-[#829078]">Your family, together</p><h1 className="mt-2 text-3xl font-semibold">{mode==="login"?"Welcome back":"Create your account"}</h1><p className="mt-3 text-sm leading-6 text-[#737c72]">Sign in to create and manage your private family tree.</p><button onClick={google} disabled={busy} className="mt-7 w-full rounded-full border border-[#dce2d7] bg-white px-5 py-3.5 text-sm font-semibold hover:bg-[#f6f7f2] disabled:opacity-60">Continue with Google</button><div className="my-5 flex items-center gap-3 text-xs text-[#9aa195]"><span className="h-px flex-1 bg-[#e7e9e0]"/>or continue with email<span className="h-px flex-1 bg-[#e7e9e0]"/></div><form onSubmit={submit} className="space-y-4"><label className="block text-sm font-medium">Email<input type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} className="mt-2 w-full rounded-xl border border-[#dfe4da] bg-white px-4 py-3 outline-none focus:border-[#78916c]" placeholder="you@example.com"/></label><label className="block text-sm font-medium">Password<input type="password" required minLength={8} autoComplete={mode==="login"?"current-password":"new-password"} value={password} onChange={e=>setPassword(e.target.value)} className="mt-2 w-full rounded-xl border border-[#dfe4da] bg-white px-4 py-3 outline-none focus:border-[#78916c]" placeholder="At least 8 characters"/></label>{message&&<p role="status" className="rounded-xl bg-[#f1f4eb] p-3 text-sm text-[#526b4d]">{message}</p>}<button disabled={busy} className="w-full rounded-full bg-[#244b38] px-5 py-3.5 text-sm font-semibold text-white hover:bg-[#183727] disabled:opacity-60">{busy?"Please wait...":mode==="login"?"Sign in":"Create account"}</button></form><p className="mt-6 text-center text-sm text-[#737c72]">{mode==="login"?"New to Vansh?":"Already have an account?"} <button onClick={()=>{setMode(mode==="login"?"signup":"login");setMessage("");}} className="font-semibold text-[#416246] underline">{mode==="login"?"Create account":"Sign in"}</button></p><p className="mt-5 text-center text-xs text-[#9aa195]">Your family tree is private. We never make it public by default.</p></div></main>;
}
