import Link from "next/link";

const features = [
  { icon: "✳", title: "Your family, beautifully connected", body: "Build an interactive family tree across generations. Explore branches, open profiles, and see how everyone is connected." },
  { icon: "अ", title: "Made for Indian families", body: "Understand relationships with Hindi and English kinship labels, including paternal and maternal sides." },
  { icon: "✦", title: "Preserve every story", body: "Keep family memories, photographs, milestones, and the stories you want future generations to remember." },
];

export default function Home() {
  return (
    <main className="min-h-screen overflow-hidden bg-[#f8f7f2] text-[#24372d]">
      <header className="mx-auto flex max-w-7xl items-center justify-between px-6 py-6 lg:px-10">
        <Link href="/" className="flex items-center gap-3 text-xl font-semibold tracking-tight"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-[#244b38] text-xl text-white">V</span> vansh</Link>
        <div className="flex items-center gap-3"><span className="hidden text-sm text-[#6e786f] sm:block">Your family. Your story.</span><Link href="/app/tree" className="rounded-full bg-[#244b38] px-5 py-3 text-sm font-medium text-white transition hover:bg-[#183727]">Open family tree ↗</Link></div>
      </header>
      <section className="mx-auto grid max-w-7xl items-center gap-12 px-6 pb-20 pt-12 lg:grid-cols-[1.02fr_.98fr] lg:px-10 lg:pb-28 lg:pt-20">
        <div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[#dce4d9] bg-white/70 px-4 py-2 text-xs font-medium text-[#55715d]"><span className="h-2 w-2 rounded-full bg-[#6c9a6f]"/> A home for your family history</div><h1 className="max-w-2xl text-5xl font-semibold leading-[1.08] tracking-[-.045em] sm:text-6xl lg:text-7xl">Every family has a <span className="font-serif italic text-[#78916c]">story.</span><br/>Keep yours growing.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-[#68746a]">Bring generations together in one private, beautiful family tree. Remember your roots, celebrate your people, and pass your stories forward.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/app/tree" className="rounded-full bg-[#244b38] px-7 py-4 text-sm font-semibold text-white shadow-lg shadow-[#244b38]/15 transition hover:-translate-y-0.5">Start your family tree <span className="ml-2">→</span></Link><a href="#how-it-works" className="rounded-full border border-[#d7ddd3] bg-white px-7 py-4 text-sm font-semibold text-[#344b3b] hover:bg-[#f0f2eb]">Explore Vansh</a></div><div className="mt-8 flex items-center gap-3 text-sm text-[#778077]"><span className="text-lg">⌘</span> Private by design · Hindi + English</div></div>
        <div className="relative mx-auto w-full max-w-xl"><div className="absolute -inset-8 rounded-[3rem] bg-[#e8ecdf] blur-2xl"/><div className="relative rounded-[2rem] border border-white bg-[#fffefa] p-5 shadow-[0_30px_100px_-45px_rgba(36,75,56,.35)] sm:p-8"><div className="mb-7 flex items-center justify-between"><div><p className="text-xs uppercase tracking-[.18em] text-[#899185]">A glimpse of your roots</p><h2 className="mt-1 text-xl font-semibold">The Patel Family</h2></div><span className="rounded-full bg-[#edf2e8] px-3 py-1.5 text-xs text-[#52714f]">3 generations</span></div><div className="flex flex-col items-center"><Person name="Dadaji & Dadiji" sub="Generation 1" initials="द"/><div className="h-8 w-px bg-[#cbd5c5]"/><div className="h-px w-[70%] bg-[#cbd5c5]"/><div className="grid w-full grid-cols-2"><div className="flex flex-col items-center"><div className="h-7 w-px bg-[#cbd5c5]"/><Person name="Papa & Mummy" sub="Generation 2" initials="प"/></div><div className="flex flex-col items-center"><div className="h-7 w-px bg-[#cbd5c5]"/><Person name="Chacha & Chachi" sub="Generation 2" initials="च"/></div></div><div className="h-7 w-px bg-[#cbd5c5]"/><div className="rounded-2xl border border-[#c3d2b9] bg-[#f0f5eb] px-8 py-4 text-center shadow-sm"><div className="mx-auto mb-2 grid h-10 w-10 place-items-center rounded-full bg-[#dce8d3] font-serif text-lg text-[#35583b]">D</div><p className="font-semibold">You & your family</p><p className="mt-1 text-xs text-[#71816c]">Your story continues here</p></div></div><p className="mt-7 text-center text-xs text-[#9aa195]">Illustrative family tree · Make it your own</p></div></div>
      </section>
      <section id="how-it-works" className="border-t border-[#e8e9e1] bg-white/60 px-6 py-20 lg:px-10"><div className="mx-auto max-w-7xl"><div className="max-w-xl"><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#829078]">Rooted in connection</p><h2 className="mt-4 text-3xl font-semibold tracking-tight sm:text-4xl">More than names and lines.</h2><p className="mt-4 leading-7 text-[#737c72]">A thoughtful space to connect your people, understand your relationships, and keep family memories close.</p></div><div className="mt-12 grid gap-5 md:grid-cols-3">{features.map((f,i)=><article key={f.title} className="rounded-3xl border border-[#e7e9e0] bg-[#fffefa] p-7 transition hover:-translate-y-1 hover:shadow-lg hover:shadow-[#244b38]/5"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-[#edf2e8] text-xl text-[#416246]">{f.icon}</div><p className="mt-7 text-xs text-[#9aa195]">0{i+1}</p><h3 className="mt-2 text-lg font-semibold">{f.title}</h3><p className="mt-3 text-sm leading-6 text-[#737c72]">{f.body}</p></article>)}</div></div></section>
      <footer className="mx-auto flex max-w-7xl flex-col gap-3 px-6 py-8 text-xs text-[#92998e] sm:flex-row sm:items-center sm:justify-between lg:px-10"><span>© 2026 Vansh · Every family has a story.</span><span>Made with care for the stories that make us.</span></footer>
    </main>
  );
}

function Person({ name, sub, initials }: { name: string; sub: string; initials: string }) {
  return <div className="z-10 flex min-w-0 flex-col items-center rounded-2xl border border-[#e7e9e0] bg-white px-3 py-4 text-center shadow-sm sm:min-w-[170px] sm:px-5"><div className="mb-2 grid h-10 w-10 place-items-center rounded-full bg-[#f1e9db] font-serif text-lg text-[#876d4e]">{initials}</div><p className="text-xs font-semibold sm:text-sm">{name}</p><p className="mt-1 text-[10px] text-[#9aa195]">{sub}</p></div>;
}
